### ISSUE TITLE
Non-deterministic failure of EtcdCluster deployment in air-gapped on-prem environments

### ISSUE THREAD

**Issue by ytsarev** [AbsaOSS/ohmyglb#107]
During on-prem tests we encountered a situation during `EtcdCluster` creation with `etcd-operator` is not picking up the overridden private registry image reference and still tries to pull `quay.io/coreos/etcd` during cluster creation.

In one cluster it 'fixed' itself automatically by redeployment in another cluster the issue persisted so we had to manually patch `EtcdCluster` resource.

Definitely worth investigation as it can complicate on-prem installations.

Also we need to figure out if the problem affects only 1.14 cluster deployment workaround ( see https://github.com/AbsaOSS/ohmyglb/blob/master/Makefile#L114 ) or it is also a case for standard stable deployment target ( https://github.com/AbsaOSS/ohmyglb/blob/master/Makefile#L104 )

**Comment by ytsarev** [comment]
it's totally weird (tm)
I ran a simple local test.

* Repository value was intentionally modified
```
git diff
diff --git a/chart/ohmyglb/values.yaml b/chart/ohmyglb/values.yaml
index c800087..dce5b00 100644
--- a/chart/ohmyglb/values.yaml
+++ b/chart/ohmyglb/values.yaml
@@ -38,8 +38,8 @@ etcd-operator:
       tag: v0.9.4
   etcdCluster:
     image:
-      repository: quay.io/coreos/etcd
-      tag: v3.2.25
+      repository: wtf
+    version: 3.2.25
```

* Test shell script with 100 times iteration testing the modified value propagation was created
```
 cat etcd-repo-template-test.sh
for i in {1..100}
do
    echo "Trying $i time..."
    helm -n ohmyglb template ohmyglb chart/ohmyglb -f chart/ohmyglb/values.yaml 2>/dev/null |grep wtf
done
```
* Execution results look not really promising
```
sh etcd-repo-template-test.sh
Trying 1 time...
  repository: "wtf"
Trying 2 time...
Trying 3 time...
Trying 4 time...
Trying 5 time...
Trying 6 time...
Trying 7 time...
Trying 8 time...
Trying 9 time...
Trying 10 time...
Trying 11 time...
Trying 12 time...
Trying 13 time...
Trying 14 time...
Trying 15 time...
Trying 16 time...
Trying 17 time...
Trying 18 time...
Trying 19 time...
Trying 20 time...
Trying 21 time...
Trying 22 time...
  repository: "wtf"
Trying 23 time...
Trying 24 time...
  repository: "wtf"
Trying 25 time...
Trying 26 time...
Trying 27 time...
Trying 28 time...
Trying 29 time...
Trying 30 time...
Trying 31 time...
Trying 32 time...
Trying 33 time...
Trying 34 time...
Trying 35 time...
Trying 36 time...
Trying 37 time...
Trying 38 time...
Trying 39 time...
Trying 40 time...
Trying 41 time...
Trying 42 time...
Trying 43 time...
Trying 44 time...
Trying 45 time...
Trying 46 time...
Trying 47 time...
Trying 48 time...
Trying 49 time...
Trying 50 time...
Trying 51 time...
Trying 52 time...
  repository: "wtf"
Trying 53 time...
Trying 54 time...
  repository: "wtf"
Trying 55 time...
Trying 56 time...
Trying 57 time...
Trying 58 time...
Trying 59 time...
Trying 60 time...
Trying 61 time...
Trying 62 time...
Trying 63 time...
Trying 64 time...
Trying 65 time...
Trying 66 time...
Trying 67 time...
  repository: "wtf"
Trying 68 time...
Trying 69 time...
Trying 70 time...
Trying 71 time...
Trying 72 time...
Trying 73 time...
Trying 74 time...
Trying 75 time...
Trying 76 time...
Trying 77 time...
Trying 78 time...
  repository: "wtf"
Trying 79 time...
Trying 80 time...
Trying 81 time...
Trying 82 time...
Trying 83 time...
  repository: "wtf"
Trying 84 time...
  repository: "wtf"
Trying 85 time...
Trying 86 time...
  repository: "wtf"
Trying 87 time...
Trying 88 time...
Trying 89 time...
Trying 90 time...
Trying 91 time...
Trying 92 time...
Trying 93 time...
Trying 94 time...
Trying 95 time...
Trying 96 time...
Trying 97 time...
Trying 98 time...
Trying 99 time...
Trying 100 time...
  repository: "wtf"
```

As you can see proper propagation happens in totally non-deterministic way.

**Comment by donovanmuller** [comment]
@ytsarev I tried this 1000 times consecutively and did not experience the issue at all:

What version of `helm` are you using?

```
$ helm version
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

**Comment by donovanmuller** [comment]
Just upgraded `helm` locally and still cannot reproduce even once:

```
$ helm version
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

**Comment by ytsarev** [comment]
@donovanmuller thanks a ton for the check. Unfortunately I'm running latest and still hitting the issue

```
 helm version
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

**Comment by ytsarev** [comment]
@donovanmuller just in case, expected result is to `repository: "wtf"` on each execution - is it what you get ?

**Comment by ytsarev** [comment]
Mystery solved ,  I had prepackaged `chart/ohmyglb/charts/etcd-operator-0.10.2.tgz` lying around left from old style dependency deployment. And it was not visible because of proper .gitignore

Apparently helm was randomly choosing between pacakged`chart/ohmyglb/charts/etcd-operator-0.10.2.tgz` and unpackaged ``chart/ohmyglb/charts/etcd-operator` effectively overriding `EtcdCluster` resource from time to time

After removal of `chart/ohmyglb/charts/etcd-operator-0.10.2.tgz` everything is consistent

Still there is minor inconsistency with version propagation which we inherited from upstream. Will send PR soon
