### ISSUE TITLE
Posssible Routing Peering Capabilities BGP protocols

### ISSUE THREAD

**Issue by ZakAnderson** [AbsaOSS/ohmyglb#33]
The problem statement is as follows:

1. Can ohmyglb be built in such a way it would peer with a routable network using either bgp (Border Gateway Protocols)
2. Could you use the AS Number Private Ranges or an ospf Area config
3. Can you use authenticationon either BGP or Ospf to make sure it can be secured for only peer to peer session establishment
4. Can you use an ACL which can be used to present network ip's via the above two routing protocols
5. I am asking if the project feature request can be possibly looked at for this as this would mean that you could be location agnostic

**Comment by ytsarev** [comment]
@MightyAnderson it's too hardcore networking for me but i'll gradually give it a try :) Does https://metallb.universe.tf/concepts/bgp/  look close to the desired scenario ?

**Comment by MightyAnderson** [comment]
Hi

This is similar to what is requested as your already doing the Load balancing taking the idea to peer with any BGP capable or ospf capable device can give full dynamic IP address injection thus also elevating the strengths of the solution to a DNS provider which can mean you control the name and map it to an ip but then also enable the functionality for what is know as “anycast” ip in a network

#featurerequest

**Comment by donovanmuller** [comment]
As per discussions with @ZakAnderson this feature is best implemented in a separate project.
