### ISSUE TITLE
Add full end to end integration tests to build pipeline

### ISSUE THREAD

**Issue by donovanmuller** [AbsaOSS/ohmyglb#48]
Existing build pipelines should be enhanced with full end to end integration tests running in managed Kubernetes clusters.

The goal of these tests would be to simulate:

* real world scenarios deploying to multiple managed Kubernete clusters (potentially across different clouds)
* exercise tests of the various load balancing strategies
* simulate the various failure scenarios including split brain examples
* verify the edge DNS integrations across the supported providers

These tests should be triggered at strategic and meaningful points in the development flow, considering that this test suite could take considerable time to run to completion.

**Comment by ytsarev** [comment]
I've marked https://github.com/AbsaOSS/ohmyglb/pull/91 to resolve this one. #92 was created to address EdgeDNS testing as a separate effort
